### ISSUE TITLE
Make visualization responsive (i.e. resize based on the page width)

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow.github.com#173]
It would be great if the visualization div occupies 100% of the blog post width. (Not more.) For thinner screens:

1. The legend moves to below or above the graph, so that the graph occupies nearly the full width of the visualization div
2. The bars resize based on the screen width

**Comment by galvanic** [comment]
Bars resize based on screen width: [feat: Set width of whole chart to the width of the parent element](https://github.com/snowplow/d3-attribution-visualization/commit/e38feb20622cb86d3ff5d5c62e6ad8d2817286b5)

**Comment by yalisassoon** [comment]
Cool!

On Mon, Jun 29, 2015 at 1:42 PM, justine <notifications@github.com> wrote:

> Bars resize based on screen width: feat: Set width of whole chart to the
> width of the parent element
> <https://github.com/snowplow/d3-attribution-visualization/commit/e38feb20622cb86d3ff5d5c62e6ad8d2817286b5>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow.github.com/issues/173#issuecomment-116643525>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by yalisassoon** [comment]
Hey @galvanic - just testing this now...

Viz looks great at full width:

![image](https://cloud.githubusercontent.com/assets/201147/8415630/320a0170-1e98-11e5-8271-c93f50237058.png)

And at a reduced width:

![image](https://cloud.githubusercontent.com/assets/201147/8415651/4d61b076-1e98-11e5-8d6b-2cdd92d73bbf.png)

But loading the page in smaller windows and the viz spills over:

![image](https://cloud.githubusercontent.com/assets/201147/8415659/65331834-1e98-11e5-85d5-c08ad4b356b6.png)

Also note that the legend doesn't move to above / below the viz - think this is necessary if it so look readable on a mobile...

**Comment by galvanic** [comment]
Commit: [feat: legend is on the side if screen big enough otherwise not](https://github.com/snowplow/d3-attribution-visualization/commit/75d5ca9236ef190662fee058cac1a910c69c0f2d)

See live [here](http://bl.ocks.org/galvanic/raw/2eb5043ea7c2dd845975/75d5ca9236ef190662fee058cac1a910c69c0f2d/) (Not yet updated in GTM)

Change minimum screen width [here](https://github.com/snowplow/d3-attribution-visualization/blob/75d5ca9236ef190662fee058cac1a910c69c0f2d/journeysChart.js#L76) (Currently at 550px) -> this feels a bit hacky but I'm not sure how to do it with bootstrap. I think the names of classes in the svg would need to be changed.
